lib/birma_web/router.ex
defmodule BirmaWeb.Router do
  use BirmaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BirmaWeb.Plugs.Veil.UserId
    plug BirmaWeb.Plugs.Veil.User
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BirmaWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/catalog", PageController, :catalog
  end

  scope "/pantry" do
    pipe_through [:browser, BirmaWeb.Plugs.Veil.Authenticate]
    get "/", BirmaWeb.PantryController, :index
    get "/manage", BirmaWeb.PantryController, :manage
    post "/add", BirmaWeb.PantryController, :add
    get "/generate", BirmaWeb.PantryController, :generate
    post "/generate", BirmaWeb.PantryController, :generate_meals
  end

  scope "/api" do
    pipe_through([:api])

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: BirmaWeb.Schema,
      interface: :simple
  end

  # Default Routes for Veil
  scope "/veil", BirmaWeb.Veil do
    pipe_through(:browser)

    get("/users/new", UserController, :new)
    post("/users", UserController, :create)
    get("/sessions/new/:request_unique_id", SessionController, :create)
    get("/sessions/signout/:session_unique_id", SessionController, :delete)
  end
end

lib/birma_web/views/layout_view.ex
defmodule BirmaWeb.LayoutView do
  use BirmaWeb, :view
end

lib/birma_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Birma · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li>
              <%= if veil_user_id = assigns[:veil_user_id] do %>
                Authenticated as <%= veil_user_id %>
                <a href="<%= Routes.session_path(@conn, :delete, @session_unique_id) %>">Sign out</a>
              <% else %>
                <a href="<%= Routes.user_path(@conn, :new) %>">Sign in</a>
              <% end %>
            </li>
            <li><%= link "Catalog", to: Routes.page_path(@conn, :catalog) %></li>
            <li><%= link "Pantry", to: Routes.pantry_path(@conn, :index) %></li>
            <li><%= link "Graphiql", to: "/api/graphiql" %></li>
          </ul>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>